version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - 'db'
  db:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'shopper'
      POSTGRES_PASSWORD: 'shopper'
      POSTGRES_DB: 'shopper'